version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install boto3 sagemaker

  build:
    commands:
      - echo "Deploying SageMaker endpoint..."
      - |
        python3 << 'EOF'
        import boto3
        import json
        import os
        
        sagemaker = boto3.client('sagemaker')
        
        # Get latest approved model
        response = sagemaker.list_model_packages(
            ModelPackageGroupName='house-price-model-group',
            ModelApprovalStatus='Approved',
            SortBy='CreationTime',
            SortOrder='Descending',
            MaxResults=1
        )
        
        if response['ModelPackageSummaryList']:
            model_package_arn = response['ModelPackageSummaryList'][0]['ModelPackageArn']
            print(f"Deploying model: {model_package_arn}")
            
            # Create endpoint config
            endpoint_config_name = f"house-price-endpoint-config-{int(__import__('time').time())}"
            sagemaker.create_endpoint_config(
                EndpointConfigName=endpoint_config_name,
                ProductionVariants=[{
                    'VariantName': 'primary',
                    'ModelName': model_package_arn.split('/')[-1],
                    'InitialInstanceCount': 1,
                    'InstanceType': 'ml.t2.medium',
                    'InitialVariantWeight': 1.0
                }]
            )
            
            # Create/update endpoint
            endpoint_name = 'house-price-endpoint'
            try:
                sagemaker.update_endpoint(
                    EndpointName=endpoint_name,
                    EndpointConfigName=endpoint_config_name
                )
                print(f"Updated endpoint: {endpoint_name}")
            except:
                sagemaker.create_endpoint(
                    EndpointName=endpoint_name,
                    EndpointConfigName=endpoint_config_name
                )
                print(f"Created endpoint: {endpoint_name}")
        else:
            print("No approved models found")
        EOF

  post_build:
    commands:
      - echo "Deployment completed"